# Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install: true
script:
  - cd jaxb-ri
  - mvn --update-snapshots --strict-checksums --activate-profiles staging,oss-release clean install